services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    hostname: monitoring.palvir.dev
    command:
      - "--storage.path=/var/lib/alloy/data"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "/etc/alloy/config.alloy"
    user: "0"
    ports: 
      - 12345:12345
      - 4318:4318  # OTLP gRPC receiver
      - 4319:4319  # OTLP HTTP receiver
      - 5140:5140  # OTLP Syslog receiver (TCP)
      - 5140:5140/udp  # OTLP Syslog receiver (UDP)
      - 5514:5514  # Loki Syslog receiver (TCP)
      - 5514:5514/udp  # Loki Syslog receiver (UDP)
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - ./alloy/data:/var/lib/alloy/data
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /var/log:/var/log:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /run/udev/data:/run/udev/data:ro
    restart: unless-stopped
  loki:
    image: grafana/loki:latest
    user: "0"
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki/data:/loki
    restart: unless-stopped
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: "0"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/data:/tmp/tempo
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
    restart: unless-stopped
  proxmox:
    image: prompve/prometheus-pve-exporter:latest
    restart: unless-stopped
    ports:
      - "9221:9221" 
    environment:
      PVE_USER: ${PVE_USER}
      PVE_PASSWORD: ${PVE_PASSWORD}
      PVE_VERIFY_SSL: "false"
    command: 
      - "--web.listen-address=0.0.0.0:9221"
      - "--no-collector.config"
  nginx:
    image: nginx/nginx-prometheus-exporter
    restart: unless-stopped
    command:
      - ${NGINX_URI}
    ports:
      - "9113:9113"
  pgsql:
    image: prometheuscommunity/postgres-exporter
    restart: unless-stopped
    environment:
      - DATA_SOURCE_NAME=${PGSQL}
    ports:
      - "9187:9187"
  adguard:
    image: ebrianne/adguard-exporter
    restart: unless-stopped
    ports:
      - "9617:9617"
    environment:
      - adguard_protocol=${ADG_PROTO}
      - adguard_hostname=${ADG_PROTO}
      - adguard_username=${ADG_USR}
      - adguard_password=${ADG_PASS}
      - interval=10s
      - log_limit=10000
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - "--web.enable-lifecycle"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAF_USR}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAF_PASS}
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
volumes:
  prom_data:
  grafana_data:
